### PR TITLE
LPS- 57040 [TECHNICAL SUPPORT] Japanese input conversion is auto-confirmed randomly

### PR DESCRIPTION
**Pull request by yuhai**
Hi Byrån, @daledotshan, @hhuijser

The issue explanation is as the following:

The issue can't be reproduced on ee-4.4.x.
In ckeditor_4.1.3, the issue can be reproduced.
In 4.2 ( 2013.07.18), the issue can't be reproduced. So I think the issue was fixed in 4.2. 

I checked 4.2 fix and try to use the current fix commit and it can solve the issue

The issue was fixed in http://dev.ckeditor.com/ticket/9794. I backport the related commit so that I don't merge any conflict. The previous two commits are not fix in 9794. But 9794's fix was based on the two commits. Please check whether it is right.

Regards,
Hai

### CODE REVIEW

**Comment by blzaugg** [comment]
Effectively you are backporting these correct?

http://dev.ckeditor.com/ticket/10131
http://dev.ckeditor.com/ticket/10315
http://dev.ckeditor.com/ticket/9794

Was 5608b82578b647111d63ac9573f2e66fb8d910e3 not needed as part of 10315?

**Comment by yuhai** [comment]
Hi Byrån,

yes, I am backporting the three tickets. 

In my test, the current issue can be solved by using these backport fix and I didn't backport https://github.com/blzaugg/liferay-ckeditor/commit/5608b82578b647111d63ac9573f2e66fb8d910e3.
I don't know whether it is needed. Could you please help check it? 

Regards,
Hai

**Comment by blzaugg** [comment]
I was never able to replicate this issue using MIE. But the backport looks good and doesn't cause any errors. I added 5608b82 and the changelog. I'll push the Portal changes to Brian, but I'd like you to double check that everything is okay.

**Comment by blzaugg** [comment]
https://github.com/brianchandotcom/liferay-portal-ee/pull/10772

**Pull request closed without merging**
