### PR TITLE
LPS-59936 alter regex to exlude non ascii characters and whitesapce

### PR DESCRIPTION
**Pull request by dustinryerson**
@SamZiemer 

Relevant ticket:
https://issues.liferay.com/browse/LPS-59936

### CODE REVIEW

**Comment by blzaugg** [comment]
@SamZiemer can you also submit a ticket and PR to CKEditor and link the CK ticket in the LPS?

https://dev.ckeditor.com/newticket
https://github.com/ckeditor/ckeditor-dev/pulls

**Comment by SamZiemer** [comment]
Sure, I'll do that now. I was not sure if we wanted to review the fix first to make sure it looks good before submitting to CKEditor

**Comment by SamZiemer** [comment]
@blzaugg 

I have created the ticket and the pull request and posted them on the ticket.

https://dev.ckeditor.com/ticket/13887#ticket
https://github.com/ckeditor/ckeditor-dev/pull/229

**Comment by blzaugg** [comment]
Thank you.

**Comment by blzaugg** [comment]
Perfect ticket thank you.

**Comment by blzaugg** [comment]
@SamZiemer how did you determine the ASCII range?

**Comment by blzaugg** [comment]
I'm thinking it may need to be reduced down to `21-7E`, to remove control codes and the space character.

See: https://en.wikipedia.org/wiki/ASCII#ASCII_control_code_chart

What do you think?

I considered `20-7E` but I'm not sure if `\s` will get caught. Maybe it still will.

**Comment by SamZiemer** [comment]
When I determined the range, I just went from one end of the ascii table to another. I believe you have a much better solution though.

**Pull request merged**
